---
# Copyright (C) 2020 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: '{{ copr_reposync_include_repo }} - Set systemd unit name fact'
  ansible.builtin.set_fact:
    copr_reposync_fact_unit: '{{ copr_reposync_service_name }}@{{ copr_reposync_name.replace("/", "-") }}-{{ copr_reposync_include_repo }}'

- name: '{{ copr_reposync_include_repo }} - Create systemd service drop-in directory'
  ansible.builtin.file:
    path: '/etc/systemd/system/{{ copr_reposync_fact_unit }}.service.d'
    state: directory
    mode: 0755
    owner: root
    group: root

- name: '{{ copr_reposync_include_repo }} - Create systemd service configuration'
  ansible.builtin.template:
    src: override.conf.j2
    dest: '/etc/systemd/system/{{ copr_reposync_fact_unit }}.service.d/override.conf'
    mode: 0644
    owner: root
    group: root
  register: copr_reposync_register_service

- name: '{{ copr_reposync_include_repo }} - Execute systemd service'
  ansible.builtin.systemd:
    name: '{{ copr_reposync_fact_unit }}'
    state: started
    enabled: no
  when:
    - (copr_reposync_register_service is changed) or
      (copr_reposync_exec_sync | bool)  # noqa no-handler
    - (ansible_service_mgr | default('systemd')) == 'systemd'

- name: '{{ copr_reposync_include_repo }} - Include tasks to setup systemd timer'
  ansible.builtin.include_tasks: reposync_timer.yml
  when: copr_reposync_timer | bool
