---
# Copyright (C) 2020 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: '{{ copr_reposync_include_repo }} - Enable systemd timer'
  ansible.builtin.systemd:
    name: '{{ copr_reposync_fact_unit }}.timer'
    state: started
    enabled: yes
  when: (ansible_service_mgr | default('systemd')) == 'systemd'
