---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Converge
  hosts: all

  vars:
    # Use https://copr.fedorainfracloud.org/coprs/ganto/jo/ for testing
    copr_reposync_name: 'ganto/jo'

    # Only mirror repositories matching our distribution
    copr_reposync_distributions:
      - '{{ "fedora" if ansible_distribution == "Fedora" else "epel" }}'

  roles:
    - role: ganto.copr_reposync
