---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    # Install apache2 to server repository mirror
    - name: Install Apache2 httpd server
      ansible.builtin.package:
        name: httpd
        state: present

    # Work-around flanky private tmp mount
    - name: Remove PrivateTmp configuration in httpd service
      ansible.builtin.lineinfile:
        path: /usr/lib/systemd/system/httpd.service
        line: 'PrivateTmp=true'
        state: absent

    - name: Enable and start httpd service
      ansible.builtin.systemd:
        # Reload modified httpd.service
        daemon_reload: true
        enabled: true
        name: httpd.service
        state: started
