---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all

  tasks:
    - name: Check GPG public key and repository file
      ansible.builtin.stat:
        path: '{{ item }}'
      loop:
        - '/var/www/html/ganto/jo/pubkey.gpg'
        - '/var/www/html/ganto/jo/ganto-jo-{{ "fedora" if ansible_distribution == "Fedora"
                                                       else "epel" }}.repo'
      register: verify_repo_files

    - name: GPG public key and repository file must exist
      ansible.builtin.assert:
        quiet: true
        that: '{{ item.stat.exists }}'
      loop: '{{ verify_repo_files.results }}'
      loop_control:
        label: '{{ item.item }}'

    - name: Download repository file to local yum repos path
      ansible.builtin.get_url:
        url: 'http://localhost/ganto/jo/ganto-jo-{{ "fedora" if ansible_distribution == "Fedora"
                                                             else "epel" }}.repo'
        dest: '/etc/yum.repos.d/_copr-mirror_ganto-jo.repo'
        mode: 0644

    - name: Install package from COPR repository mirror
      ansible.builtin.package:
        name: jo
        state: present
