---
# Copyright (C) 2021-2025 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
  options:
    requirements-file: molecule/docker/collections.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: True
    pre_build_image: True
provisioner:
  name: ansible
  log: True
  options:
    vvv: True
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # TODO: idempotence still broken
    - verify
    - cleanup
    - destroy
