---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Master
on:
  push:
    branches:
      - master
    tags:
      - '*'

permissions:
  contents: read

defaults:
  run:
    working-directory: 'ganto.copr_reposync'

jobs:

  update-galaxy:
    name: Update-Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: 'ganto.copr_reposync'
          persist-credentials: false

      - name: Set up Python 3.
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        env:
          REPOSITORY: ${{ github.repository }}
        run: >
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          "${REPOSITORY%/*}" "${REPOSITORY#*/}"
