---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Master
on:
  push:
    branches:
      - master
    tags:
      - '*'

permissions:
  contents: read

defaults:
  run:
    working-directory: 'ganto.copr_reposync'

jobs:

  update-galaxy:
    name: Update-Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: 'ganto.copr_reposync'
          persist-credentials: false

      - name: Set up Python 3.
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        env:
          REPOSITORY: ${{ github.repository }}
        run: >
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          "${REPOSITORY%/*}" "${REPOSITORY#*/}"
